version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: rollaxse
      POSTGRES_PASSWORD: Houseplant617
      POSTGRES_DB: password_vault
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

